before_script:
- set GRADLE_USER_HOME=`pwd`/.gradle
- ./gradlew
 
build:
  script:
    - C:\Users\jakit\INDIVIDUAL\tennis-website\individual-assignment-db\gradlew assemble
 
test:
  stage: test
  script:
    - ./gradlew test
 
after_script:
  - echo "End CI"
