stages:
  - build
  - test
  - sonarqube
 
build:
  stage: build
  script:
    - cd ./individual-assignment-db
    - ./gradlew assemble
  include:
    - template: Dependency-Scanning.gitlab-ci.yml

test:
  stage: test
  dependencies:
    - build
  script:
    - cd ./individual-assignment-db
    - ./gradlew test

sonarqube:
 stage: sonarqube
 dependencies:
   - test
 script:
   - cd ./individual-assignment-db
   - ./gradlew sonarqube

deploy:
  stage: deploy
  dependencies:
    - sonarqube
  script:
    - docker build -t tennis-website-spring .  #building the image
    - docker run --rm -p 8080:8080 tennis-website-spring #running the docker; --rm - deleting a container every time after a crash or stop

after_script:
  - echo "End CI"

