stages:
  - build
  - test
  - sonarqube
  - cypress
  - deploy

build:
  stage: build
  script:
    - cd ./individual-assignment-db
    - ./gradlew assemble

test:
  stage: test
  dependencies:
    - build
  script:
    - cd ./individual-assignment-db
    - ./gradlew test

sonarqube:
 stage: sonarqube
 dependencies:
   - test
 script:
   - cd ./individual-assignment-db
   - ./gradlew sonarqube

cypress:
  stage: cypress
  dependencies:
    - sonarqube
  script:
   - npm install cypress --save-dev
   - npm run cypress:open

deploy:
  stage: deploy
  dependencies:
    - cypress
  script:
    - docker build -t tennis-website-spring .  #building the image
    - docker run --rm -p 8080:8080 tennis-website-spring #running the docker; --rm - deleting a container every time after a crash or stop

after_script:
  - echo "End CI"

