stages:
  - build
  - test
 
build:
  stage: build
  script:
    - cd ./individual-assignment-db
    - ./gradlew assemble
 
test:
  stage: test
  dependencies:
    - build
  script:
    - cd ./individual-assignment-db
    - ./gradlew test
 
after_script:
  - echo "End CI"
