stages:
  - build
  - test
  - sonarqube
 
build:
  stage: build
  script:
    - cd ./individual-assignment-db
    - ./gradlew assemble
 
test:
  stage: test
  dependencies:
    - build
  script:
    - cd ./individual-assignment-db
    - ./gradlew test

sonarqube:
 stage: sonarqube
 dependencies:
   -test
 script:
   - cd ./individual-assignment-db
   - ./gradlew sonarqube

after_script:
  - echo "End CI"
